stages:
  - build
  - test

# Build the dev environment
devenv-ci:
  stage: build
  tags:
    - nixos-verifiable-oracles-runner
  script:
    - devenv ci

# Run golang tests
test:
  stage: test
  tags:
    - nixos-verifiable-oracles-runner
  before_script:
    - devenv shell ganache-start
  script:
    - source ganache.env
    - devenv shell gotestsum --junitfile report.xml --format testname -- -tags=integration ./...
  after_script:
    - source ganache.env
    - devenv shell ganache-stop "${GANACHE}"
    - devenv shell ganache instances list
    - rm ganache.env
  artifacts:
    when: always
    paths:
      - report.xml
    reports:
      junit: report.xml
